# Generated by Django 5.0.7 on 2025-04-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('or_sec_no', models.CharField(db_index=True, max_length=255, unique=True)),
                ('descriptions', models.TextField()),
            ],
            options={
                'db_table': 'tbl_violation',
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citation_no', models.CharField(db_index=True, max_length=25, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('full_address', models.CharField(blank=True, max_length=255, null=True)),
                ('driv_lic', models.CharField(blank=True, max_length=100, null=True)),
                ('exp_date', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_owner', models.CharField(blank=True, max_length=150, null=True)),
                ('reg_address', models.CharField(blank=True, max_length=255, null=True)),
                ('veh_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('crt_reg_no', models.CharField(blank=True, max_length=50, null=True)),
                ('franc_no', models.CharField(blank=True, max_length=15, null=True)),
                ('place_of_viola', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_viola', models.CharField(blank=True, max_length=50, null=True)),
                ('time_of_viola', models.CharField(blank=True, max_length=50, null=True)),
                ('amounts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('app_officer', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('violations', models.ManyToManyField(blank=True, db_table='tbl_citation_violations', to='citation.violation')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'db_table': 'tbl_citation',
            },
        ),
    ]
