# Generated by Django 5.0.7 on 2025-04-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='violations',
            field=models.ManyToManyField(blank=True, db_table='tbl_citation_violations', related_name='citations', to='citation.violation'),
        ),
    ]
